<a href="https://colab.research.google.com/github/BhoomikaSheth/PythonBasicNotes/blob/main/Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Pandas

In [ ]:
import pandas as pd
# series-- 1d, dataframe ---2 2d,68,74

In [ ]:
s1=pd.Series([23,78,90,23,56,68,74])
s1

0    23
1    78
2    90
3    23
4    56
5    68
6    74
dtype: int64

In [ ]:
s1.head()

0    23
1    78
2    90
3    23
4    56
dtype: int64

In [ ]:
s1.tail()

2    90
3    23
4    56
5    68
6    74
dtype: int64

In [ ]:
s1.iloc[3:5]

3    23
4    56
dtype: int64

In [ ]:
s1[3:5]

3    23
4    56
dtype: int64

In [ ]:
s2=s1*3
s2

0     69
1    234
2    270
3     69
4    168
5    204
6    222
dtype: int64

In [ ]:
s1

0    23
1    78
2    90
3    23
4    56
5    68
6    74
dtype: int64

In [ ]:
s1.head(2)

0    23
1    78
dtype: int64

In [ ]:
s1.head(-3)

0    23
1    78
2    90
3    23
dtype: int64

In [ ]:
s1.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
s1.index=["a","b","c","d","e","f","g"]
s1

a    23
b    78
c    90
d    23
e    56
f    68
g    74
dtype: int64

In [ ]:
s3=pd.Series(data=[23,45,67,89,90,12,89],index=["a","b","c","d","e","f","g"])
s3

a    23
b    45
c    67
d    89
e    90
f    12
g    89
dtype: int64

In [ ]:
s3.unique()

array([23, 45, 67, 89, 90, 12])

In [ ]:
s3[3]

89

In [ ]:
s3["d"]

89

In [ ]:
s3[1:5:2]

b    45
d    89
dtype: int64

In [ ]:
s3[[1,2,5]]

b    45
c    67
f    12
dtype: int64

In [ ]:
d=pd.DataFrame([[2,4,6,8],[12,14,16,18],[22,24,26,28]])
d

    0   1   2   3
0   2   4   6   8
1  12  14  16  18
2  22  24  26  28

In [ ]:
d.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
d.columns

RangeIndex(start=0, stop=4, step=1)

In [ ]:
d.columns=["col1","col2","col3","col4"]
d

   col1  col2  col3  col4
0     2     4     6     8
1    12    14    16    18
2    22    24    26    28

In [ ]:
d.iloc[:,0] # one col

0     2
1    12
2    22
Name: col1, dtype: int64

In [ ]:
d["col1"] # one col

0     2
1    12
2    22
Name: col1, dtype: int64

In [ ]:
d.iloc[1,:] # one row

col1    12
col2    14
col3    16
col4    18
Name: 1, dtype: int64

In [ ]:
d

   col1  col2  col3  col4
0     2     4     6     8
1    12    14    16    18
2    22    24    26    28

In [ ]:
d.iloc[1:3,1:3]

   col2  col3
1    14    16
2    24    26

In [ ]:
d.iloc[1:,1:3] # sliced up part of table

   col2  col3
1    14    16
2    24    26

In [ ]:
d.iloc[1:,1:4] # sliced up part of table

   col2  col3  col4
1    14    16    18
2    24    26    28

In [ ]:
d.loc[d["col1"]>10,:] # row-array of random row nums, row-condition, row-slice, col- col, col- array of cols

   col1  col2  col3  col4
1    12    14    16    18
2    22    24    26    28

In [ ]:
d.loc[d["col1"]>10,"col2"] # row-array of random row nums, row-condition, row-slice, col- col, col- array of cols

1    14
2    24
Name: col2, dtype: int64

In [ ]:
d.loc[d["col1"]>10,"col1"] # row-array of random row nums, row-condition, row-slice, col- col, col- array of cols

1    12
2    22
Name: col1, dtype: int64

In [ ]:
d.iloc[2,3]

28

In [ ]:
d.loc[1,:]

col1    12
col2    14
col3    16
col4    18
Name: 1, dtype: int64

In [ ]:
d.loc[1,"col1"]

12

In [ ]:
d.loc[1,["col2","col3"]]

col2    14
col3    16
Name: 1, dtype: int64

In [ ]:
d.loc[[0,2],"col1"]

0     2
2    22
Name: col1, dtype: int64

In [ ]:
d.loc[[0,2],["col1","col2"]]

   col1  col2
0     2     4
2    22    24

In [ ]:
filter=d["col1"]>10
d.loc[filter]

   col1  col2  col3  col4
1    12    14    16    18
2    22    24    26    28

In [ ]:
# make a series of numbers from 0 to 100 and filter out all perfect squares from it

In [ ]:
# make a dataframe of numbers from 0 to 100, squares from 0 to 100, cubes from 0 to 100.
#l=[0,1,2,3...100]

# l=[]
# for i in range(1,101):
#     l.append(i)
# l

#l=[i**3 for i in range(0,101)]


# from this datafram filter out even squares

#filter out odd cubes

# filter out squares and cubes of all prime numbers

In [ ]:
d=[i for i in range(0,101)]

In [ ]:
d

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [ ]:
import pandas as pd

In [ ]:
d=pd.Series(d)

In [ ]:
d

0        0
1        1
2        2
3        3
4        4
      ...
96      96
97      97
98      98
99      99
100    100
Length: 101, dtype: int64

In [ ]:
import numpy as np

In [ ]:
np.sqrt(d)

0       0.000000
1       1.000000
2       1.414214
3       1.732051
4       2.000000
         ...
96      9.797959
97      9.848858
98      9.899495
99      9.949874
100    10.000000
Length: 101, dtype: float64

In [ ]:
for i in d:
  sr=int(np.sqrt(i))
  if sr*sr==i:
    print(i)

0
1
4
9
16
25
36
49
64
81
100

In [ ]:
import pandas as pd
import numpy as np
d=pd.Series([i for i in range(0,101)])
filter=round(np.sqrt(d))*round(np.sqrt(d))==d
d[filter]

0        0
1        1
4        4
9        9
16      16
25      25
36      36
49      49
64      64
81      81
100    100
dtype: int64

In [ ]:
# filter=int(np.sqrt(d))*int(np.sqrt(d))==d
# d[filter]

In [ ]:
f=pd.DataFrame([[i for i in range(0,101)],[i**2 for i in range(0,101)],[i**3 for i in range(0,101)]])
f

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
1,0,1,4,9,16,25,36,49,64,81,...,8281,8464,8649,8836,9025,9216,9409,9604,9801,10000
2,0,1,8,27,64,125,216,343,512,729,...,753571,778688,804357,830584,857375,884736,912673,941192,970299,1000000

In [ ]:
# from this datafram filter out even squares

#filter out odd cubes

# filter out squares and cubes of all prime numbers

In [ ]:
sq=f.iloc[1:2,:]
sq

# for i in sq:
#   esq=i%2
#   if esq==0:
#     print(i)

filter=sq%2==0
sq[filter]

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
1,0,NaN,4,NaN,16,NaN,36,NaN,64,NaN,...,NaN,8464,NaN,8836,NaN,9216,NaN,9604,NaN,10000

In [ ]:
import pandas as pd
f=pd.DataFrame([[i for i in range(0,101)],[i**2 for i in range(0,101)],[i**3 for i in range(0,101)]])
f

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
1,0,1,4,9,16,25,36,49,64,81,...,8281,8464,8649,8836,9025,9216,9409,9604,9801,10000
2,0,1,8,27,64,125,216,343,512,729,...,753571,778688,804357,830584,857375,884736,912673,941192,970299,1000000

In [ ]:
df=pd.DataFrame({"linear":[i for i in range(1,101)],"squares":[i**2 for i in range(1,101)],"cubes":[i**3 for i in range(1,101)]})
df

    linear  squares    cubes
0        1        1        1
1        2        4        8
2        3        9       27
3        4       16       64
4        5       25      125
..     ...      ...      ...
95      96     9216   884736
96      97     9409   912673
97      98     9604   941192
98      99     9801   970299
99     100    10000  1000000

[100 rows x 3 columns]

In [ ]:
# from this datafram filter out even squares

#filter out odd cubes

# filter out squares and cubes of all prime numbers

In [ ]:
np.nan

nan

In [ ]:
import pandas as pd

In [ ]:
import numpy as np
df2=pd.DataFrame({"col1":[np.nan,78,12,np.nan],"col2":["a","a",np.nan,"a"],"col3":[100,np.nan,200,400]})
df2

   col1 col2   col3
0   NaN    a  100.0
1  78.0    a    NaN
2  12.0  NaN  200.0
3   NaN    a  400.0

In [ ]:
#df2.isnull()
df2.isna().sum()

col1    2
col2    1
col3    1
dtype: int64

In [ ]:
filter=df2["col1"].isnull()==True
df2.loc[filter,"col1"]=df2["col1"].mean()
df2

   col1 col2   col3
0  45.0    a  100.0
1  78.0    a    NaN
2  12.0  NaN  200.0
3  45.0    a  400.0

In [ ]:
filter1=df2["col3"].isnull()==True
df2.loc[filter1,"col3"]=df2["col3"].mean()
df2

   col1 col2        col3
0  45.0    a  100.000000
1  78.0    a  233.333333
2  12.0  NaN  200.000000
3  45.0    a  400.000000

In [ ]:
filter2=df2["col2"].isnull()==True
df2.loc[filter2,"col2"]=df2["col2"].mode()[0]
df2

   col1 col2        col3
0  45.0    a  100.000000
1  78.0    a  233.333333
2  12.0    a  200.000000
3  45.0    a  400.000000

In [ ]:
filter2

0    False
1    False
2     True
3    False
Name: col2, dtype: bool

In [ ]:
m=df2["col2"].mode()
m

0    a
dtype: object

In [ ]:
df2.loc[filter2,"col2"]=df2["col2"].mode()
df2

   col1 col2        col3
0  45.0    a  100.000000
1  78.0    a  233.333333
2  12.0  NaN  200.000000
3  45.0    a  400.000000

In [ ]:
df2["col2"].fillna(value=df2["col2"].mode()[0],inplace=True)
df2

   col1 col2        col3
0  45.0    a  100.000000
1  78.0    a  233.333333
2  12.0    a  200.000000
3  45.0    a  400.000000

In [ ]:
m

0    a
dtype: object

In [ ]:
df2["col1"].mean()

45.0

In [ ]:
df2["col2"].mode()[0]

'a'

In [ ]:
df2

   col1 col2        col3
0  45.0    a  100.000000
1  78.0    a  233.333333
2  12.0    a  200.000000
3  45.0    a  400.000000

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      float64
 1   col2    4 non-null      object
 2   col3    4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 224.0+ bytes

In [ ]:
df2["col2"].value_counts()

a    4
Name: col2, dtype: int64

In [ ]:
df2["gender"]=pd.Series(data=["MALE","FEMALE","MALE","FEMALE"],index=df2.index) # data frma insert new col at end
df2

   col1 col2        col3  gender
0  45.0    a  100.000000    MALE
1  78.0    a  233.333333  FEMALE
2  12.0    a  200.000000    MALE
3  45.0    a  400.000000  FEMALE

In [ ]:
df2.insert(loc=1,column="size",value=pd.Series(data=["S","M","L","M"],index=df2.index))
df2

   col1 size col2        col3  gender
0  45.0    S    a  100.000000    MALE
1  78.0    M    a  233.333333  FEMALE
2  12.0    L    a  200.000000    MALE
3  45.0    M    a  400.000000  FEMALE

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      float64
 1   size    4 non-null      object
 2   col2    4 non-null      object
 3   col3    4 non-null      float64
 4   gender  4 non-null      object
dtypes: float64(2), object(3)
memory usage: 288.0+ bytes

In [ ]:
df2["size"].value_counts()

M    2
S    1
L    1
Name: size, dtype: int64

In [ ]:
size_int={"S":1,"M":2,"L":3}
df2["size"]=df2["size"].map(size_int)
df2

   col1  size col2        col3  gender
0  45.0     1    a  100.000000    MALE
1  78.0     2    a  233.333333  FEMALE
2  12.0     3    a  200.000000    MALE
3  45.0     2    a  400.000000  FEMALE

In [ ]:
col2_int={"a":1}
df2["col2"]=df2["col2"].map(col2_int)
df2

   col1  size  col2        col3  gender
0  45.0     1     1  100.000000    MALE
1  78.0     2     1  233.333333  FEMALE
2  12.0     3     1  200.000000    MALE
3  45.0     2     1  400.000000  FEMALE

In [ ]:
df2["gender"]=df2["gender"].map({"MALE":1,"FEMALE":2})
df2

   col1  size  col2        col3  gender
0  45.0     1     1  100.000000       1
1  78.0     2     1  233.333333       2
2  12.0     3     1  200.000000       1
3  45.0     2     1  400.000000       2

In [ ]:
df2["Landscape"]=pd.Series(data=["Mountains","Hills","Plains","Hills"],index=df2.index)
df2

   col1  size  col2        col3  gender  Landscape
0  45.0     1     1  100.000000       1  Mountains
1  78.0     2     1  233.333333       2      Hills
2  12.0     3     1  200.000000       1     Plains
3  45.0     2     1  400.000000       2      Hills

In [ ]:
pd.get_dummies(df2["Landscape"],dtype=int)

   Hills  Mountains  Plains
0      0          1       0
1      1          0       0
2      0          0       1
3      1          0       0

In [ ]:
ld=pd.get_dummies(df2["Landscape"],dtype=int,drop_first=True)
ld

   Mountains  Plains
0          1       0
1          0       0
2          0       1
3          0       0

In [ ]:
df3=pd.concat([df2,ld],axis=1)
df3

   col1  size  col2        col3  gender  Landscape  Mountains  Plains
0  45.0     1     1  100.000000       1  Mountains          1       0
1  78.0     2     1  233.333333       2      Hills          0       0
2  12.0     3     1  200.000000       1     Plains          0       1
3  45.0     2     1  400.000000       2      Hills          0       0

In [ ]:
df3.drop("Landscape",inplace=True,axis=1)
df3

   col1  size  col2        col3  gender  Mountains  Plains
0  45.0     1     1  100.000000       1          1       0
1  78.0     2     1  233.333333       2          0       0
2  12.0     3     1  200.000000       1          0       1
3  45.0     2     1  400.000000       2          0       0

In [ ]:
df3.describe()

            col1      size  col2        col3   gender  Mountains  Plains
count   4.000000  4.000000   4.0    4.000000  4.00000       4.00    4.00
mean   45.000000  2.000000   1.0  233.333333  1.50000       0.25    0.25
std    26.944387  0.816497   0.0  124.721913  0.57735       0.50    0.50
min    12.000000  1.000000   1.0  100.000000  1.00000       0.00    0.00
25%    36.750000  1.750000   1.0  175.000000  1.00000       0.00    0.00
50%    45.000000  2.000000   1.0  216.666667  1.50000       0.00    0.00
75%    53.250000  2.250000   1.0  275.000000  2.00000       0.25    0.25
max    78.000000  3.000000   1.0  400.000000  2.00000       1.00    1.00

In [ ]:
g1=df3.groupby("gender")
g1

In [ ]:
g1.describe()

        col1                                                   size       ...  \
       count  mean        std   min    25%   50%    75%   max count mean  ...
gender                                                                    ...
1        2.0  28.5  23.334524  12.0  20.25  28.5  36.75  45.0   2.0  2.0  ...
2        2.0  61.5  23.334524  45.0  53.25  61.5  69.75  78.0   2.0  2.0  ...

       Mountains      Plains
             75%  max  count mean       std  min   25%  50%   75%  max
gender
1           0.75  1.0    2.0  0.5  0.707107  0.0  0.25  0.5  0.75  1.0
2           0.00  0.0    2.0  0.0  0.000000  0.0  0.00  0.0  0.00  0.0

[2 rows x 48 columns]

In [ ]:
g1.get_group(1)

   col1  size  col2   col3  gender  Mountains  Plains
0  45.0     1     1  100.0       1          1       0
2  12.0     3     1  200.0       1          0       1

In [ ]:
g1.get_group(2)

   col1  size  col2        col3  gender  Mountains  Plains
1  78.0     2     1  233.333333       2          0       0
3  45.0     2     1  400.000000       2          0       0

In [ ]:
g1.mean()

        col1  size  col2        col3  Mountains  Plains
gender
1       28.5   2.0   1.0  150.000000        0.5     0.5
2       61.5   2.0   1.0  316.666667        0.0     0.0

In [ ]:
g1.agg({"col1":"mean"})

        col1
gender
1       28.5
2       61.5

In [ ]:
g1.agg(func={"col1":["mean","std","median"]})

        col1
        mean        std median
gender
1       28.5  23.334524   28.5
2       61.5  23.334524   61.5

In [ ]:
g1.agg(func={"col1":["mean","std","median"],"col3":["mean","median"]})

        col1                          col3
        mean        std median        mean      median
gender
1       28.5  23.334524   28.5  150.000000  150.000000
2       61.5  23.334524   61.5  316.666667  316.666667

In [ ]:
df3["country"]=pd.Series(data=["India","US","India","UK"],index=df3.index)
df3

   col1  size  col2        col3  gender  Mountains  Plains country
0  45.0     1     1  100.000000       1          1       0   India
1  78.0     2     1  233.333333       2          0       0      US
2  12.0     3     1  200.000000       1          0       1   India
3  45.0     2     1  400.000000       2          0       0      UK

In [ ]:
df3.select_dtypes(int)

   size  col2  gender  Mountains  Plains
0     1     1       1          1       0
1     2     1       2          0       0
2     3     1       1          0       1
3     2     1       2          0       0

In [ ]:
df3.select_dtypes((int,float))

   col1  size  col2        col3  gender  Mountains  Plains
0  45.0     1     1  100.000000       1          1       0
1  78.0     2     1  233.333333       2          0       0
2  12.0     3     1  200.000000       1          0       1
3  45.0     2     1  400.000000       2          0       0

In [ ]:
def func(series):
    result=series.mean()/(series.max()-series.min())
    return result

df3.iloc[:,[0]].apply(func,axis=0)  # col 0, row 1

col1    0.681818
dtype: float64

In [ ]:
df3.iloc[:,[0,3]].apply(func,axis=0)  # col 0, row 1

col1    0.681818
col3    0.777778
dtype: float64

In [ ]:
df3["data"]=pd.Series(data=[np.nan,"d1",np.nan,"d3"],index=df3.index)
df3

   col1  size  col2        col3  gender  Mountains  Plains country data
0  45.0     1     1  100.000000       1          1       0   India  NaN
1  78.0     2     1  233.333333       2          0       0      US   d1
2  12.0     3     1  200.000000       1          0       1   India  NaN
3  45.0     2     1  400.000000       2          0       0      UK   d3

In [ ]:
df3.dropna()

   col1  size  col2        col3  gender  Mountains  Plains country data
1  78.0     2     1  233.333333       2          0       0      US   d1
3  45.0     2     1  400.000000       2          0       0      UK   d3

In [ ]:
df3

   col1  size  col2        col3  gender  Mountains  Plains country data
0  45.0     1     1  100.000000       1          1       0   India  NaN
1  78.0     2     1  233.333333       2          0       0      US   d1
2  12.0     3     1  200.000000       1          0       1   India  NaN
3  45.0     2     1  400.000000       2          0       0      UK   d3

In [ ]:
#bitwise &   |     ~
filter1=df3["gender"]==1
filter2=df3["country"]=="India"
df3.loc[filter1 & filter2,"col3"]

0    100.0
2    200.0
Name: col3, dtype: float64

In [ ]:
df3.loc[(df3["gender"]==1)&(df3["country"]=="India"),"col3"]

0    100.0
2    200.0
Name: col3, dtype: float64

In [ ]:
df3.loc[(df3["col1"]==45.0)|(df3["size"]>2),"col3"]

0    100.0
2    200.0
3    400.0
Name: col3, dtype: float64

In [ ]:
df3.loc[(df3["col1"]==45.0)&(df3["size"]>=2),"col3"]

3    400.0
Name: col3, dtype: float64

In [ ]:
df3.loc[~((df3["col1"]==45.0)&(df3["size"]>=2)),"col3"]

0    100.000000
1    233.333333
2    200.000000
Name: col3, dtype: float64

In [ ]:
df3.loc[(df3["size"]==1)&(df3["col2"]==1)&(df3["gender"]==1)&(df3["Mountains"]==1),"country"]

0    India
Name: country, dtype: object

In [ ]:
df3.loc[(df3["gender"]==2)&(df3["country"]=="India")]

Empty DataFrame
Columns: [col1, size, col2, col3, gender, Mountains, Plains, country, data]
Index: []

In [ ]:
df3.loc[(df3["size"]>=2)&(df3["country"]=="India")]

   col1  size  col2   col3  gender  Mountains  Plains country data
2  12.0     3     1  200.0       1          0       1   India  NaN

In [ ]:
df3.loc[((df3["size"]==1)|(df3["size"]==3))&(df3["country"]=="India")]

   col1  size  col2   col3  gender  Mountains  Plains country data
0  45.0     1     1  100.0       1          1       0   India  NaN
2  12.0     3     1  200.0       1          0       1   India  NaN

Interpreting Data Description¶
The results show 8 numbers for each column in your original dataset. The first number, the count, shows how many rows have non-missing values.

Missing values arise for many reasons. For example, the size of the 2nd bedroom wouldn't be collected when surveying a 1 bedroom house. We'll come back to the topic of missing data.

The second value is the mean, which is the average. Under that, std is the standard deviation, which measures how numerically spread out the values are.

To interpret the min, 25%, 50%, 75% and max values, imagine sorting each column from lowest to highest value. The first (smallest) value is the min. If you go a quarter way through the list, you'll find a number that is bigger than 25% of the values and smaller than 75% of the values. That is the 25% value (pronounced "25th percentile"). The 50th and 75th percentiles are defined analogously, and the max is the largest number.